"use client";
import {createClient} from "@supabase/supabase-js"; import {useEffect,useMemo,useState} from "react";
const supabase=createClient(process.env.NEXT_PUBLIC_SUPABASE_URL!,process.env.NEXT_PUBLIC_SUPABASE_ANON_KEY!);
type Opt={id:string,duration_minutes:number,price_chf:number,service_id:string}; type Service={id:string,name_fr:string,name_en:string,description_fr?:string,service_options:Opt[]};
export default function Page(){const [services,setServices]=useState<Service[]>([]),[service,setService]=useState<Service|null>(null),[option,setOption]=useState<Opt|null>(null),[date,setDate]=useState(""),[slots,setSlots]=useState<string[]>([]),[slot,setSlot]=useState(""),[name,setName]=useState(""),[email,setEmail]=useState(""),[phone,setPhone]=useState(""),[busy,setBusy]=useState(false),[done,setDone]=useState(false),[err,setErr]=useState("");
useEffect(()=>{supabase.from("services").select("id,name_fr,name_en,description_fr,service_options(id,duration_minutes,price_chf,service_id)").eq("active",true).order("sort_order").then(({data})=>setServices((data||[]) as Service[]))},[]);
useEffect(()=>{if(!option||!date)return;setSlot("");supabase.rpc("get_available_slots",{p_service_option_id:option.id,p_date:date}).then(({data,error})=>{if(error)setErr(error.message);else setSlots((data||[]).map((x:any)=>x.slot_start))})},[option,date]);
const minDate=useMemo(()=>new Date().toLocaleDateString("en-CA",{timeZone:"Europe/Zurich"}),[]);
async function book(){if(!option||!slot||!name||!email||!phone)return;setBusy(true);setErr("");const {error}=await supabase.rpc("create_public_booking",{p_service_option_id:option.id,p_name:name,p_email:email,p_phone:phone,p_start_at:slot,p_locale:"fr"});setBusy(false);if(error)setErr(error.message.includes("slot_unavailable")?"Ce créneau vient d’être réservé. Choisissez-en un autre.":error.message);else setDone(true)}
if(done)return <main><div className="success"><h1>Réservation confirmée</h1><p>Votre rendez-vous chez Anya Thai Massage est enregistré.</p></div></main>;
return <main><div className="brand"><p>Genève</p><h1>Anya Thai Massage</h1><div className="muted">Réservation en ligne</div></div><h2>1. Choisissez votre massage</h2>
{services.map(s=><div className={"card "+(service?.id===s.id?"active":"")} key={s.id} onClick={()=>{setService(s);setOption(null);setSlots([])}}><strong>{s.name_fr}</strong>{s.description_fr&&<p className="muted">{s.description_fr}</p>}{service?.id===s.id&&<div className="options">{s.service_options.sort((a,b)=>a.duration_minutes-b.duration_minutes).map(o=><button key={o.id} onClick={e=>{e.stopPropagation();setOption(o)}} style={option?.id===o.id?{background:"#2f493c",color:"white"}:{}}>{o.duration_minutes} min · CHF {o.price_chf}</button>)}</div>}</div>)}
{option&&<><h2>2. Date</h2><input type="date" min={minDate} value={date} onChange={e=>setDate(e.target.value)}/></>}
{date&&option&&<><h2>3. Heure</h2>{slots.length?<div className="grid">{slots.map(x=><button key={x} onClick={()=>setSlot(x)} style={slot===x?{background:"#2f493c",color:"white"}:{}}>{new Date(x).toLocaleTimeString("fr-CH",{timeZone:"Europe/Zurich",hour:"2-digit",minute:"2-digit"})}</button>)}</div>:<p className="muted">Aucun créneau disponible ce jour.</p>}</>}
{slot&&<><h2>4. Vos coordonnées</h2><input placeholder="Nom et prénom" value={name} onChange={e=>setName(e.target.value)}/><input type="tel" placeholder="Téléphone" value={phone} onChange={e=>setPhone(e.target.value)}/><input type="email" placeholder="E-mail" value={email} onChange={e=>setEmail(e.target.value)}/><button className="primary" disabled={busy||!name||!phone||!email} onClick={book}>{busy?"Réservation…":"Confirmer la réservation"}</button></>}{err&&<p>{err}</p>}</main>}